language: node_js
node_js:
  - lts/*
install:
  - npm ci # npm ci
script:
  - npm run build # npm run build
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: docs/.vuepress/dist
  github_token: TRAVIS_TOKEN
  keep_history: true
  on:
    branch: master